// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calcpb/calc.proto

package calcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Calculation struct {
	FirstInt             int32    `protobuf:"varint,1,opt,name=first_int,json=firstInt,proto3" json:"first_int,omitempty"`
	SecondInt            int32    `protobuf:"varint,2,opt,name=second_int,json=secondInt,proto3" json:"second_int,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculation) Reset()         { *m = Calculation{} }
func (m *Calculation) String() string { return proto.CompactTextString(m) }
func (*Calculation) ProtoMessage()    {}
func (*Calculation) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_c77cadaaaaf821d4, []int{0}
}
func (m *Calculation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculation.Unmarshal(m, b)
}
func (m *Calculation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculation.Marshal(b, m, deterministic)
}
func (dst *Calculation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculation.Merge(dst, src)
}
func (m *Calculation) XXX_Size() int {
	return xxx_messageInfo_Calculation.Size(m)
}
func (m *Calculation) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculation.DiscardUnknown(m)
}

var xxx_messageInfo_Calculation proto.InternalMessageInfo

func (m *Calculation) GetFirstInt() int32 {
	if m != nil {
		return m.FirstInt
	}
	return 0
}

func (m *Calculation) GetSecondInt() int32 {
	if m != nil {
		return m.SecondInt
	}
	return 0
}

type CalculationRequest struct {
	Calculation          *Calculation `protobuf:"bytes,1,opt,name=calculation,proto3" json:"calculation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CalculationRequest) Reset()         { *m = CalculationRequest{} }
func (m *CalculationRequest) String() string { return proto.CompactTextString(m) }
func (*CalculationRequest) ProtoMessage()    {}
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_c77cadaaaaf821d4, []int{1}
}
func (m *CalculationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculationRequest.Unmarshal(m, b)
}
func (m *CalculationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculationRequest.Marshal(b, m, deterministic)
}
func (dst *CalculationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculationRequest.Merge(dst, src)
}
func (m *CalculationRequest) XXX_Size() int {
	return xxx_messageInfo_CalculationRequest.Size(m)
}
func (m *CalculationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculationRequest proto.InternalMessageInfo

func (m *CalculationRequest) GetCalculation() *Calculation {
	if m != nil {
		return m.Calculation
	}
	return nil
}

type CalculationResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculationResponse) Reset()         { *m = CalculationResponse{} }
func (m *CalculationResponse) String() string { return proto.CompactTextString(m) }
func (*CalculationResponse) ProtoMessage()    {}
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_c77cadaaaaf821d4, []int{2}
}
func (m *CalculationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculationResponse.Unmarshal(m, b)
}
func (m *CalculationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculationResponse.Marshal(b, m, deterministic)
}
func (dst *CalculationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculationResponse.Merge(dst, src)
}
func (m *CalculationResponse) XXX_Size() int {
	return xxx_messageInfo_CalculationResponse.Size(m)
}
func (m *CalculationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculationResponse proto.InternalMessageInfo

func (m *CalculationResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeNumberDecompRequest struct {
	NumberToDecomp       int32    `protobuf:"varint,1,opt,name=numberToDecomp,proto3" json:"numberToDecomp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecompRequest) Reset()         { *m = PrimeNumberDecompRequest{} }
func (m *PrimeNumberDecompRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompRequest) ProtoMessage()    {}
func (*PrimeNumberDecompRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_c77cadaaaaf821d4, []int{3}
}
func (m *PrimeNumberDecompRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompRequest.Unmarshal(m, b)
}
func (m *PrimeNumberDecompRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompRequest.Marshal(b, m, deterministic)
}
func (dst *PrimeNumberDecompRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompRequest.Merge(dst, src)
}
func (m *PrimeNumberDecompRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompRequest.Size(m)
}
func (m *PrimeNumberDecompRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompRequest proto.InternalMessageInfo

func (m *PrimeNumberDecompRequest) GetNumberToDecomp() int32 {
	if m != nil {
		return m.NumberToDecomp
	}
	return 0
}

type PrimeNumberDecompResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecompResponse) Reset()         { *m = PrimeNumberDecompResponse{} }
func (m *PrimeNumberDecompResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompResponse) ProtoMessage()    {}
func (*PrimeNumberDecompResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_c77cadaaaaf821d4, []int{4}
}
func (m *PrimeNumberDecompResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompResponse.Unmarshal(m, b)
}
func (m *PrimeNumberDecompResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompResponse.Marshal(b, m, deterministic)
}
func (dst *PrimeNumberDecompResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompResponse.Merge(dst, src)
}
func (m *PrimeNumberDecompResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompResponse.Size(m)
}
func (m *PrimeNumberDecompResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompResponse proto.InternalMessageInfo

func (m *PrimeNumberDecompResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Calculation)(nil), "calculator.Calculation")
	proto.RegisterType((*CalculationRequest)(nil), "calculator.CalculationRequest")
	proto.RegisterType((*CalculationResponse)(nil), "calculator.CalculationResponse")
	proto.RegisterType((*PrimeNumberDecompRequest)(nil), "calculator.PrimeNumberDecompRequest")
	proto.RegisterType((*PrimeNumberDecompResponse)(nil), "calculator.PrimeNumberDecompResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculationServiceClient is the client API for CalculationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculationServiceClient interface {
	Calculate(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error)
	PrimeNumberDecomp(ctx context.Context, in *PrimeNumberDecompRequest, opts ...grpc.CallOption) (CalculationService_PrimeNumberDecompClient, error)
}

type calculationServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculationServiceClient(cc *grpc.ClientConn) CalculationServiceClient {
	return &calculationServiceClient{cc}
}

func (c *calculationServiceClient) Calculate(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error) {
	out := new(CalculationResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculationService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculationServiceClient) PrimeNumberDecomp(ctx context.Context, in *PrimeNumberDecompRequest, opts ...grpc.CallOption) (CalculationService_PrimeNumberDecompClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculationService_serviceDesc.Streams[0], "/calculator.CalculationService/PrimeNumberDecomp", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculationServicePrimeNumberDecompClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculationService_PrimeNumberDecompClient interface {
	Recv() (*PrimeNumberDecompResponse, error)
	grpc.ClientStream
}

type calculationServicePrimeNumberDecompClient struct {
	grpc.ClientStream
}

func (x *calculationServicePrimeNumberDecompClient) Recv() (*PrimeNumberDecompResponse, error) {
	m := new(PrimeNumberDecompResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculationServiceServer is the server API for CalculationService service.
type CalculationServiceServer interface {
	Calculate(context.Context, *CalculationRequest) (*CalculationResponse, error)
	PrimeNumberDecomp(*PrimeNumberDecompRequest, CalculationService_PrimeNumberDecompServer) error
}

func RegisterCalculationServiceServer(s *grpc.Server, srv CalculationServiceServer) {
	s.RegisterService(&_CalculationService_serviceDesc, srv)
}

func _CalculationService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculationServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculationService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculationServiceServer).Calculate(ctx, req.(*CalculationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculationService_PrimeNumberDecomp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculationServiceServer).PrimeNumberDecomp(m, &calculationServicePrimeNumberDecompServer{stream})
}

type CalculationService_PrimeNumberDecompServer interface {
	Send(*PrimeNumberDecompResponse) error
	grpc.ServerStream
}

type calculationServicePrimeNumberDecompServer struct {
	grpc.ServerStream
}

func (x *calculationServicePrimeNumberDecompServer) Send(m *PrimeNumberDecompResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculationService",
	HandlerType: (*CalculationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _CalculationService_Calculate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomp",
			Handler:       _CalculationService_PrimeNumberDecomp_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calcpb/calc.proto",
}

func init() { proto.RegisterFile("calcpb/calc.proto", fileDescriptor_calc_c77cadaaaaf821d4) }

var fileDescriptor_calc_c77cadaaaaf821d4 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x82, 0xa1, 0x99, 0x80, 0xd0, 0x11, 0xb4, 0x56, 0xfc, 0x60, 0x51, 0xf1, 0x62, 0x94,
	0xf6, 0xe4, 0xb5, 0x7a, 0xc9, 0xa5, 0x4a, 0xf5, 0xe4, 0x45, 0x9a, 0xed, 0x08, 0x0b, 0xc9, 0x6e,
	0xdc, 0xdd, 0xf8, 0x23, 0xfd, 0x55, 0xd2, 0xdd, 0x84, 0xa6, 0x6a, 0xec, 0x69, 0x77, 0xde, 0x9b,
	0x79, 0xf3, 0x1e, 0x0c, 0xf4, 0xf9, 0x3c, 0xe7, 0x65, 0x76, 0xb3, 0x7c, 0x92, 0x52, 0x2b, 0xab,
	0x10, 0x96, 0xff, 0x2a, 0x9f, 0x5b, 0xa5, 0x59, 0x0a, 0xf1, 0x7d, 0x5d, 0x09, 0x25, 0xf1, 0x08,
	0xa2, 0x77, 0xa1, 0x8d, 0x7d, 0x13, 0xd2, 0x0e, 0x82, 0xb3, 0xe0, 0x6a, 0x67, 0xd6, 0x73, 0x40,
	0x2a, 0x2d, 0x1e, 0x03, 0x18, 0xe2, 0x4a, 0x2e, 0x1c, 0xbb, 0xed, 0xd8, 0xc8, 0x23, 0xa9, 0xb4,
	0xec, 0x11, 0xb0, 0x25, 0x35, 0xa3, 0x8f, 0x8a, 0x8c, 0xc5, 0x3b, 0x88, 0xf9, 0x0a, 0x75, 0x9a,
	0xf1, 0xe8, 0x20, 0x59, 0x59, 0x48, 0xda, 0x43, 0xed, 0x5e, 0x76, 0x0d, 0x7b, 0x6b, 0x82, 0xa6,
	0x54, 0xd2, 0x10, 0xee, 0x43, 0xa8, 0xc9, 0x54, 0x79, 0x63, 0xb0, 0xae, 0xd8, 0x04, 0x06, 0x4f,
	0x5a, 0x14, 0x34, 0xad, 0x8a, 0x8c, 0xf4, 0x03, 0x71, 0x55, 0x94, 0x8d, 0x8b, 0x4b, 0xd8, 0x95,
	0x0e, 0x7e, 0x51, 0x9e, 0xa8, 0x67, 0x7f, 0xa0, 0x6c, 0x0c, 0x87, 0x7f, 0x68, 0xfc, 0xbf, 0x78,
	0xf4, 0x15, 0xac, 0x25, 0x7f, 0x26, 0xfd, 0x29, 0x38, 0xe1, 0x14, 0xa2, 0x06, 0x25, 0x3c, 0xe9,
	0x4a, 0xec, 0x0d, 0x0e, 0x4f, 0x3b, 0x79, 0xbf, 0x9c, 0x6d, 0xe1, 0x02, 0xfa, 0xbf, 0xbc, 0xe1,
	0x79, 0x7b, 0xae, 0x2b, 0xfe, 0xf0, 0x62, 0x43, 0x57, 0xb3, 0xe3, 0x36, 0x98, 0xf4, 0x5e, 0x43,
	0x7f, 0x31, 0x59, 0xe8, 0xae, 0x65, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x12, 0x30, 0xd2, 0xe3,
	0x42, 0x02, 0x00, 0x00,
}
