// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calcpb/calc.proto

package calcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Calculation struct {
	FirstInt             int32    `protobuf:"varint,1,opt,name=first_int,json=firstInt,proto3" json:"first_int,omitempty"`
	SecondInt            int32    `protobuf:"varint,2,opt,name=second_int,json=secondInt,proto3" json:"second_int,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculation) Reset()         { *m = Calculation{} }
func (m *Calculation) String() string { return proto.CompactTextString(m) }
func (*Calculation) ProtoMessage()    {}
func (*Calculation) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{0}
}
func (m *Calculation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculation.Unmarshal(m, b)
}
func (m *Calculation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculation.Marshal(b, m, deterministic)
}
func (dst *Calculation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculation.Merge(dst, src)
}
func (m *Calculation) XXX_Size() int {
	return xxx_messageInfo_Calculation.Size(m)
}
func (m *Calculation) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculation.DiscardUnknown(m)
}

var xxx_messageInfo_Calculation proto.InternalMessageInfo

func (m *Calculation) GetFirstInt() int32 {
	if m != nil {
		return m.FirstInt
	}
	return 0
}

func (m *Calculation) GetSecondInt() int32 {
	if m != nil {
		return m.SecondInt
	}
	return 0
}

type CalculationRequest struct {
	Calculation          *Calculation `protobuf:"bytes,1,opt,name=calculation,proto3" json:"calculation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CalculationRequest) Reset()         { *m = CalculationRequest{} }
func (m *CalculationRequest) String() string { return proto.CompactTextString(m) }
func (*CalculationRequest) ProtoMessage()    {}
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{1}
}
func (m *CalculationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculationRequest.Unmarshal(m, b)
}
func (m *CalculationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculationRequest.Marshal(b, m, deterministic)
}
func (dst *CalculationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculationRequest.Merge(dst, src)
}
func (m *CalculationRequest) XXX_Size() int {
	return xxx_messageInfo_CalculationRequest.Size(m)
}
func (m *CalculationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculationRequest proto.InternalMessageInfo

func (m *CalculationRequest) GetCalculation() *Calculation {
	if m != nil {
		return m.Calculation
	}
	return nil
}

type CalculationResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculationResponse) Reset()         { *m = CalculationResponse{} }
func (m *CalculationResponse) String() string { return proto.CompactTextString(m) }
func (*CalculationResponse) ProtoMessage()    {}
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{2}
}
func (m *CalculationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculationResponse.Unmarshal(m, b)
}
func (m *CalculationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculationResponse.Marshal(b, m, deterministic)
}
func (dst *CalculationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculationResponse.Merge(dst, src)
}
func (m *CalculationResponse) XXX_Size() int {
	return xxx_messageInfo_CalculationResponse.Size(m)
}
func (m *CalculationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculationResponse proto.InternalMessageInfo

func (m *CalculationResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeNumberDecompRequest struct {
	NumberToDecomp       int32    `protobuf:"varint,1,opt,name=numberToDecomp,proto3" json:"numberToDecomp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecompRequest) Reset()         { *m = PrimeNumberDecompRequest{} }
func (m *PrimeNumberDecompRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompRequest) ProtoMessage()    {}
func (*PrimeNumberDecompRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{3}
}
func (m *PrimeNumberDecompRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompRequest.Unmarshal(m, b)
}
func (m *PrimeNumberDecompRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompRequest.Marshal(b, m, deterministic)
}
func (dst *PrimeNumberDecompRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompRequest.Merge(dst, src)
}
func (m *PrimeNumberDecompRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompRequest.Size(m)
}
func (m *PrimeNumberDecompRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompRequest proto.InternalMessageInfo

func (m *PrimeNumberDecompRequest) GetNumberToDecomp() int32 {
	if m != nil {
		return m.NumberToDecomp
	}
	return 0
}

type PrimeNumberDecompResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecompResponse) Reset()         { *m = PrimeNumberDecompResponse{} }
func (m *PrimeNumberDecompResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompResponse) ProtoMessage()    {}
func (*PrimeNumberDecompResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{4}
}
func (m *PrimeNumberDecompResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompResponse.Unmarshal(m, b)
}
func (m *PrimeNumberDecompResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompResponse.Marshal(b, m, deterministic)
}
func (dst *PrimeNumberDecompResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompResponse.Merge(dst, src)
}
func (m *PrimeNumberDecompResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompResponse.Size(m)
}
func (m *PrimeNumberDecompResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompResponse proto.InternalMessageInfo

func (m *PrimeNumberDecompResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ComputeAverageRequest struct {
	Number               float32  `protobuf:"fixed32,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAverageRequest) Reset()         { *m = ComputeAverageRequest{} }
func (m *ComputeAverageRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeAverageRequest) ProtoMessage()    {}
func (*ComputeAverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{5}
}
func (m *ComputeAverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAverageRequest.Unmarshal(m, b)
}
func (m *ComputeAverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAverageRequest.Marshal(b, m, deterministic)
}
func (dst *ComputeAverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAverageRequest.Merge(dst, src)
}
func (m *ComputeAverageRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeAverageRequest.Size(m)
}
func (m *ComputeAverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAverageRequest proto.InternalMessageInfo

func (m *ComputeAverageRequest) GetNumber() float32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type ComputeAverageResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAverageResponse) Reset()         { *m = ComputeAverageResponse{} }
func (m *ComputeAverageResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeAverageResponse) ProtoMessage()    {}
func (*ComputeAverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{6}
}
func (m *ComputeAverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAverageResponse.Unmarshal(m, b)
}
func (m *ComputeAverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAverageResponse.Marshal(b, m, deterministic)
}
func (dst *ComputeAverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAverageResponse.Merge(dst, src)
}
func (m *ComputeAverageResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeAverageResponse.Size(m)
}
func (m *ComputeAverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAverageResponse proto.InternalMessageInfo

func (m *ComputeAverageResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type FindMaxRequest struct {
	Number               float32  `protobuf:"fixed32,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaxRequest) Reset()         { *m = FindMaxRequest{} }
func (m *FindMaxRequest) String() string { return proto.CompactTextString(m) }
func (*FindMaxRequest) ProtoMessage()    {}
func (*FindMaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{7}
}
func (m *FindMaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaxRequest.Unmarshal(m, b)
}
func (m *FindMaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaxRequest.Marshal(b, m, deterministic)
}
func (dst *FindMaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaxRequest.Merge(dst, src)
}
func (m *FindMaxRequest) XXX_Size() int {
	return xxx_messageInfo_FindMaxRequest.Size(m)
}
func (m *FindMaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaxRequest proto.InternalMessageInfo

func (m *FindMaxRequest) GetNumber() float32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FindMaxResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaxResponse) Reset()         { *m = FindMaxResponse{} }
func (m *FindMaxResponse) String() string { return proto.CompactTextString(m) }
func (*FindMaxResponse) ProtoMessage()    {}
func (*FindMaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_072bd83c936a8127, []int{8}
}
func (m *FindMaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaxResponse.Unmarshal(m, b)
}
func (m *FindMaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaxResponse.Marshal(b, m, deterministic)
}
func (dst *FindMaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaxResponse.Merge(dst, src)
}
func (m *FindMaxResponse) XXX_Size() int {
	return xxx_messageInfo_FindMaxResponse.Size(m)
}
func (m *FindMaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaxResponse proto.InternalMessageInfo

func (m *FindMaxResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Calculation)(nil), "calculator.Calculation")
	proto.RegisterType((*CalculationRequest)(nil), "calculator.CalculationRequest")
	proto.RegisterType((*CalculationResponse)(nil), "calculator.CalculationResponse")
	proto.RegisterType((*PrimeNumberDecompRequest)(nil), "calculator.PrimeNumberDecompRequest")
	proto.RegisterType((*PrimeNumberDecompResponse)(nil), "calculator.PrimeNumberDecompResponse")
	proto.RegisterType((*ComputeAverageRequest)(nil), "calculator.ComputeAverageRequest")
	proto.RegisterType((*ComputeAverageResponse)(nil), "calculator.ComputeAverageResponse")
	proto.RegisterType((*FindMaxRequest)(nil), "calculator.FindMaxRequest")
	proto.RegisterType((*FindMaxResponse)(nil), "calculator.FindMaxResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculationServiceClient is the client API for CalculationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculationServiceClient interface {
	Calculate(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error)
	PrimeNumberDecomp(ctx context.Context, in *PrimeNumberDecompRequest, opts ...grpc.CallOption) (CalculationService_PrimeNumberDecompClient, error)
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculationService_ComputeAverageClient, error)
	FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculationService_FindMaximumClient, error)
}

type calculationServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculationServiceClient(cc *grpc.ClientConn) CalculationServiceClient {
	return &calculationServiceClient{cc}
}

func (c *calculationServiceClient) Calculate(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error) {
	out := new(CalculationResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculationService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculationServiceClient) PrimeNumberDecomp(ctx context.Context, in *PrimeNumberDecompRequest, opts ...grpc.CallOption) (CalculationService_PrimeNumberDecompClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculationService_serviceDesc.Streams[0], "/calculator.CalculationService/PrimeNumberDecomp", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculationServicePrimeNumberDecompClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculationService_PrimeNumberDecompClient interface {
	Recv() (*PrimeNumberDecompResponse, error)
	grpc.ClientStream
}

type calculationServicePrimeNumberDecompClient struct {
	grpc.ClientStream
}

func (x *calculationServicePrimeNumberDecompClient) Recv() (*PrimeNumberDecompResponse, error) {
	m := new(PrimeNumberDecompResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculationServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculationService_ComputeAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculationService_serviceDesc.Streams[1], "/calculator.CalculationService/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculationServiceComputeAverageClient{stream}
	return x, nil
}

type CalculationService_ComputeAverageClient interface {
	Send(*ComputeAverageRequest) error
	CloseAndRecv() (*ComputeAverageResponse, error)
	grpc.ClientStream
}

type calculationServiceComputeAverageClient struct {
	grpc.ClientStream
}

func (x *calculationServiceComputeAverageClient) Send(m *ComputeAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculationServiceComputeAverageClient) CloseAndRecv() (*ComputeAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ComputeAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculationServiceClient) FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculationService_FindMaximumClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculationService_serviceDesc.Streams[2], "/calculator.CalculationService/FindMaximum", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculationServiceFindMaximumClient{stream}
	return x, nil
}

type CalculationService_FindMaximumClient interface {
	Send(*FindMaxRequest) error
	Recv() (*FindMaxResponse, error)
	grpc.ClientStream
}

type calculationServiceFindMaximumClient struct {
	grpc.ClientStream
}

func (x *calculationServiceFindMaximumClient) Send(m *FindMaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculationServiceFindMaximumClient) Recv() (*FindMaxResponse, error) {
	m := new(FindMaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculationServiceServer is the server API for CalculationService service.
type CalculationServiceServer interface {
	Calculate(context.Context, *CalculationRequest) (*CalculationResponse, error)
	PrimeNumberDecomp(*PrimeNumberDecompRequest, CalculationService_PrimeNumberDecompServer) error
	ComputeAverage(CalculationService_ComputeAverageServer) error
	FindMaximum(CalculationService_FindMaximumServer) error
}

func RegisterCalculationServiceServer(s *grpc.Server, srv CalculationServiceServer) {
	s.RegisterService(&_CalculationService_serviceDesc, srv)
}

func _CalculationService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculationServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculationService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculationServiceServer).Calculate(ctx, req.(*CalculationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculationService_PrimeNumberDecomp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculationServiceServer).PrimeNumberDecomp(m, &calculationServicePrimeNumberDecompServer{stream})
}

type CalculationService_PrimeNumberDecompServer interface {
	Send(*PrimeNumberDecompResponse) error
	grpc.ServerStream
}

type calculationServicePrimeNumberDecompServer struct {
	grpc.ServerStream
}

func (x *calculationServicePrimeNumberDecompServer) Send(m *PrimeNumberDecompResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculationService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculationServiceServer).ComputeAverage(&calculationServiceComputeAverageServer{stream})
}

type CalculationService_ComputeAverageServer interface {
	SendAndClose(*ComputeAverageResponse) error
	Recv() (*ComputeAverageRequest, error)
	grpc.ServerStream
}

type calculationServiceComputeAverageServer struct {
	grpc.ServerStream
}

func (x *calculationServiceComputeAverageServer) SendAndClose(m *ComputeAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculationServiceComputeAverageServer) Recv() (*ComputeAverageRequest, error) {
	m := new(ComputeAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculationService_FindMaximum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculationServiceServer).FindMaximum(&calculationServiceFindMaximumServer{stream})
}

type CalculationService_FindMaximumServer interface {
	Send(*FindMaxResponse) error
	Recv() (*FindMaxRequest, error)
	grpc.ServerStream
}

type calculationServiceFindMaximumServer struct {
	grpc.ServerStream
}

func (x *calculationServiceFindMaximumServer) Send(m *FindMaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculationServiceFindMaximumServer) Recv() (*FindMaxRequest, error) {
	m := new(FindMaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalculationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculationService",
	HandlerType: (*CalculationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _CalculationService_Calculate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomp",
			Handler:       _CalculationService_PrimeNumberDecomp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _CalculationService_ComputeAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindMaximum",
			Handler:       _CalculationService_FindMaximum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calcpb/calc.proto",
}

func init() { proto.RegisterFile("calcpb/calc.proto", fileDescriptor_calc_072bd83c936a8127) }

var fileDescriptor_calc_072bd83c936a8127 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x4f, 0xea, 0x50,
	0x10, 0x7d, 0x6d, 0xf2, 0x1a, 0x98, 0x26, 0xbc, 0x30, 0x2f, 0x8f, 0x87, 0x25, 0x7e, 0xdd, 0xa8,
	0xc1, 0x85, 0x40, 0x60, 0xe5, 0x52, 0x30, 0x26, 0x24, 0x8a, 0x06, 0x5d, 0xe9, 0xc2, 0x94, 0x32,
	0x9a, 0x26, 0xf4, 0xde, 0x7a, 0x7b, 0x4b, 0xfc, 0xe3, 0xee, 0x0d, 0xfd, 0x80, 0x16, 0x0b, 0xac,
	0xda, 0x39, 0x33, 0xe7, 0x9c, 0xc9, 0x9c, 0x5c, 0xa8, 0x3a, 0xf6, 0xcc, 0xf1, 0x27, 0xed, 0xc5,
	0xa7, 0xe5, 0x4b, 0xa1, 0x04, 0xc2, 0xe2, 0x3f, 0x9c, 0xd9, 0x4a, 0x48, 0x36, 0x04, 0x73, 0x90,
	0x54, 0xae, 0xe0, 0xd8, 0x80, 0xf2, 0x9b, 0x2b, 0x03, 0xf5, 0xea, 0x72, 0x55, 0xd7, 0x8e, 0xb4,
	0xe6, 0xef, 0x71, 0x29, 0x02, 0x86, 0x5c, 0xe1, 0x3e, 0x40, 0x40, 0x8e, 0xe0, 0xd3, 0xa8, 0xab,
	0x47, 0xdd, 0x72, 0x8c, 0x0c, 0xb9, 0x62, 0xf7, 0x80, 0x19, 0xa9, 0x31, 0x7d, 0x84, 0x14, 0x28,
	0xbc, 0x04, 0xd3, 0x59, 0xa1, 0x91, 0xa6, 0xd9, 0xfd, 0xdf, 0x5a, 0xad, 0xd0, 0xca, 0x92, 0xb2,
	0xb3, 0xec, 0x02, 0xfe, 0xe6, 0x04, 0x03, 0x5f, 0xf0, 0x80, 0xb0, 0x06, 0x86, 0xa4, 0x20, 0x9c,
	0xa5, 0x0b, 0x26, 0x15, 0xeb, 0x43, 0xfd, 0x41, 0xba, 0x1e, 0x8d, 0x42, 0x6f, 0x42, 0xf2, 0x9a,
	0x1c, 0xe1, 0xf9, 0xe9, 0x16, 0x67, 0x50, 0xe1, 0x11, 0xfc, 0x24, 0xe2, 0x46, 0xc2, 0x5d, 0x43,
	0x59, 0x0f, 0xf6, 0x0a, 0x34, 0x76, 0x18, 0xb7, 0xe1, 0xdf, 0x40, 0x78, 0x7e, 0xa8, 0xe8, 0x6a,
	0x4e, 0xd2, 0x7e, 0xa7, 0xd4, 0xb5, 0x06, 0x46, 0xac, 0x1f, 0x11, 0xf4, 0x71, 0x52, 0xb1, 0x0e,
	0xd4, 0xd6, 0x09, 0x85, 0x16, 0xfa, 0xd2, 0xa2, 0x09, 0x95, 0x1b, 0x97, 0x4f, 0xef, 0xec, 0xcf,
	0x5d, 0xda, 0xe7, 0xf0, 0x67, 0x39, 0xb9, 0x5d, 0xb4, 0xfb, 0xa5, 0xe7, 0x12, 0x7b, 0x24, 0x39,
	0x77, 0x1d, 0xc2, 0x11, 0x94, 0x53, 0x94, 0xf0, 0x60, 0x53, 0x52, 0xf1, 0x1a, 0xd6, 0xe1, 0xc6,
	0x7e, 0x6c, 0xce, 0x7e, 0xe1, 0x14, 0xaa, 0x3f, 0x6e, 0x8a, 0x27, 0x59, 0xde, 0xa6, 0xd8, 0xac,
	0xd3, 0x1d, 0x53, 0xa9, 0x47, 0x47, 0xc3, 0x17, 0xa8, 0xe4, 0x6f, 0x8a, 0xc7, 0xb9, 0xd5, 0x8a,
	0x02, 0xb2, 0xd8, 0xb6, 0x91, 0x54, 0xbc, 0xa9, 0xe1, 0x2d, 0x98, 0xc9, 0x51, 0x5d, 0x2f, 0xf4,
	0xd0, 0xca, 0xd2, 0xf2, 0xb9, 0x58, 0x8d, 0xc2, 0xde, 0x4a, 0xab, 0xa3, 0xf5, 0x4b, 0xcf, 0x46,
	0xfc, 0x28, 0x27, 0x46, 0xf4, 0x20, 0x7b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0x65, 0x51,
	0x64, 0xa5, 0x03, 0x00, 0x00,
}
